blank_issues_enabled: true
contact_links:
  - name: Security vulnerability
    url: https://2iziguard.com/.well-known/security.txt
    about: Please use coordinated disclosure for security vulnerabilities.
