<?php
declare(strict_types=1);

namespace TwoIzi\Guard\Risk;

final class ReasonCode
{
    public const NEW_SESSION = 'NEW_SESSION';
    public const SESSION_SUCCESS_HISTORY = 'SESSION_SUCCESS_HISTORY';
    public const SESSION_FAILURE_HISTORY = 'SESSION_FAILURE_HISTORY';
    public const CHALLENGE_FAILURE_HISTORY = 'CHALLENGE_FAILURE_HISTORY';
    public const NO_JS_STATE = 'NO_JS_STATE';
    public const ABNORMAL_TIMING = 'ABNORMAL_TIMING';
    public const MISSING_INTERACTION = 'MISSING_INTERACTION';
    public const NETWORK_VELOCITY = 'NETWORK_VELOCITY';
    public const SESSION_VELOCITY = 'SESSION_VELOCITY';
    public const GLOBAL_VELOCITY = 'GLOBAL_VELOCITY';
    public const ACCOUNT_VELOCITY = 'ACCOUNT_VELOCITY';
    public const APPLICATION_RISK_SIGNAL = 'APPLICATION_RISK_SIGNAL';
    public const APPLICATION_TRUST_SIGNAL = 'APPLICATION_TRUST_SIGNAL';
    public const INTERACTION_REQUIRED = 'INTERACTION_REQUIRED';
    public const INTERACTION_TOO_FAST = 'INTERACTION_TOO_FAST';
    public const CHALLENGE_INTEGRITY_FAILED = 'CHALLENGE_INTEGRITY_FAILED';
    public const HONEYPOT_TRIGGERED = 'HONEYPOT_TRIGGERED';
    public const HONEYPOT_MISSING = 'HONEYPOT_MISSING';
    public const POW_FAILED = 'POW_FAILED';
    public const TOKEN_VALID = 'TOKEN_VALID';
    public const TOKEN_INVALID = 'TOKEN_INVALID';
    public const TOKEN_INTEGRITY_FAILED = 'TOKEN_INTEGRITY_FAILED';
    public const TOKEN_REPLAY = 'TOKEN_REPLAY';
    public const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
    public const TOKEN_REVOKED = 'TOKEN_REVOKED';
    public const ACTION_MISMATCH = 'ACTION_MISMATCH';
    public const SESSION_MISMATCH = 'SESSION_MISMATCH';
    public const ORIGIN_MISMATCH = 'ORIGIN_MISMATCH';
}
